name: Upload Release Artifacts
on:
  push:
    tags:
      - "*.*.*"

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.konan
          key: ${{ runner.os }}-publish-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-publish-
            ${{ runner.os }}-

      - run: echo "Build"
      - run: echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
      - run: echo "Tag name from github.ref_name: ${{ github.ref_name }}"
      - run: gh release upload "${{ github.ref_name }}" version.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
